remove asyncio references
saaste/fmi-weather-client pull request #37
Opened 2020-10-26 20:26 UTC by anand-p-r

While integrating FMI weather sensor into [HASSIO](https://www.home-assistant.io/), CI breaks due to explicitly specified asyncio requirement in the fmi-weather-client==0.1.0 requirement. It seems that asyncio is part of core python for a long time now and hence this requirement can be removed.
Tested this locally and as per the instructions on README. It works fine.

2020-10-27 19:51 UTC, anand-p-r commented
@saaste will it be possible for you to review the change?

2020-10-28 05:50 UTC, saaste requested changes
Could you please fetch the latest changes from master and make sure the tests pass. I updated README and fixed small issues with Makefile and GitHub actions.

2020-10-28 12:16 UTC, anand-p-r commented
@saaste Thanks for fixing the tests! I had totally misunderstood the problem. The need was to remove asyncio from explicitly indicated requirements and not asyncio itself. I have rectified this and bumped up the version from 0.1.0 to 0.1.1. Please check and comment.

2020-10-28 12:54 UTC, saaste approved these changes
Good stuff and thank you for contributing!

I was working on Home Assistant FMI integration for quite a while (this is why I created this library) but I didn't finish it yet 😄  And now I am kinda too busy to continue so I'm glad to hear you are working on something similar 👏 

I'll publish the new version in few minutes ☺️

2020-10-28 12:54 UTC, merged